#!/usr/bin/env bash

# Update system packages
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Create a simple index.html file
echo "Hello World!" | sudo tee /var/www/html/index.html

# Configure Nginx for redirection
echo "
server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;

	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}

	location / {
		try_files \$uri \$uri/ =404;
	}
}
" | sudo tee /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart
