#!/bin/bash
sudo netstat -tulnep | awk 'NR>2 {print $1, $4, $7}' | sed 's/://; s|/|\t|' | awk '{system("ps -p "$NF" -o comm= | sed 1d")}' | sed 's/$/\t/'; sudo netstat -ulnep | awk 'NR>2 {print $1, $4, $7}' | sed 's/://; s|/|\t|' | awk '{system("ps -p "$NF" -o comm= | sed 1d")}' | sed 's/$/\t/'

