#!/usr/bin/env bash
# Bash script that configures Nginx server to run on :80
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart