#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely with a 2-second delay.
# - Displays "I am invincible!!!" on receiving SIGTERM.

trap 'echo "I am invincible!!!"' SIGTERM

while true
do
  echo "To infinity and beyond"
  sleep 2
done
