#!/usr/bin/env bash
# Displays specific information from the file '/etc/passwd'.
# - Displays the username, user ID, and user home directory path.

while read -r passwd; do
  echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
