#!/usr/bin/env bash
# Tells a story based on the contents of the '/etc/passwd' file.
# - Iterates through each line of the file, extracting user information.
# - Displays a narrative about each user's details: username, group, home directory, shell, user ID, password, and additional information.

while IFS=':' read -r username password uid gid info home shell; do
  echo "The user $username is part of the $gid gang,"\
  "lives in $home and rides $shell."\
  "$uid's place is protected by the passcode $password,"\
  "more info about the user here: $info"
done < "/etc/passwd"
