#!/usr/bin/env bash
# Prints "Best School" ten times, with "Hi" on the 9th iteration.

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 8 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( count++ ))
done
