#!/usr/bin/env bash
# Script: 0-use_a_private_key
# Description: Script to SSH into a server using a private key
# Author: [Your Name]
# Date: [Date of Last Update]

private_key="/path/to/your/Private_key.txt"
username="ubuntu"
server_ip="35.153.16.9"

chmod +x "$private_key"  # Ensure the private key file is executable
ssh -i "$private_key" "$username@$server_ip"
