#!/usr/bin/env bash
# Script: 0-use_a_private_key
# Description: Script to SSH into a server using a private key

private_key="~/Documents/ALX_Server/id_rsa""
username="ubuntu"
server_ip="34.232.67.183"

chmod +x "$private_key"
ssh -i "$private_key" "$username@$server_ip"
